### ISSUE TITLE
highlightjs dependency is missing from bower.json

### ISSUE THREAD

**Issue by sandipchitale** [guylabs/angular-spring-data-rest-sample#3]
highlightjs dependency is missing from bower.json

This results in 404 on the link:

.../lib/bower/highlightjs/highlight.pack.js

and buttons:
- Show me the code
- Show me the response
- Show me the processed response

do not work.

**Comment by gobled** [comment]
install highlightjs using bower and it works fine

> bower install highlightjs

**Comment by guylabs** [comment]
Hi @sandipchitale,

thanks for pointing this out. I will try to fix it asap.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @sandipchitale, 

now it should be fixed.

Thanks and regards,

Guy
